#!/bin/sh
# generate archive of all executables in sideband
# ptout.sideband -> ptout.tar.gz
# sptbinaries [ptout]
#

PREFIX=${1:-ptout}

tar czf ${PREFIX}.tar.gz ${PREFIX}.sideband $(awk ' { print $5 } ' ${PREFIX}.sideband | sort | uniq)
