#!/bin/bash
# simple test for simple pt
# needs to be run as root

set -e
set -x

failed() {
	echo FAILED
	exit 1
}
trap failed ERR 0

export LD_LIBRARY_PATH=$(pwd)/../processor-trace/lib
export PATH=$PATH:.

PREFIX=stest

EXTRA=-t

run() {
	sptcmd $EXTRA -o $PREFIX "$@" taskset -c 0 ./loop
	sptdecode --sideband ${PREFIX}.sideband --pt ${PREFIX}.0 $DARGS > ${PREFIX}.out
}

gcc -o loop loop.c -g
run
grep -q  __libc_start_main.*main stest.out
grep -q page_fault stest.out
run -c loop
grep -q  __libc_start_main.*main stest.out
grep -q page_fault stest.out
run --disretc --msr-trace --no-user
grep -q page_fault stest.out
run --no-kernel -c loop
grep -q  __libc_start_main.*main stest.out
grep -v -q page_fault stest.out

# FIXME: work around libipt bug for now on this test case
if ! ./ptfeature cyc ; then
	run --start-addr SyS_prctl --stop-addr SyS_personality
	grep -q main stest.out
fi

MAIN=$(nm loop | awk '$3 == "main" { print "0x" $1 }  ')
FINI=$(nm loop | awk '$3 == "_fini" { print "0x" $1 }  ')

if ./ptfeature filter ; then
	run --filter $MAIN,$FINI -c loop
	grep -v -q write stest.out
fi

if ./ptfeature stop ; then
	run --stop-range $MAIN,$FINI -K -c loop
	grep -q __libc_start_main stest.out
	grep -v -q -w main stest.out # main is not reached
	# XXX check for disabled message later
fi

if ./ptfeature cyc psb mtc ; then
	run --cyc 1 --mtc 3 --psb 1
	grep -q main stest.out
fi

set +x
trap "" ERR 0

echo 
echo SUCCEEDED
echo



